### ISSUE TITLE
Redis长时间未连接再次连接时报异常

### ISSUE THREAD

**Issue by CreatorMC** [CreatorMC/CreatorMCBlog#2]
错误信息：

`Redis exception; nested exception is io.lettuce.core.RedisException: java.io.IOException: 远程主机强迫关闭了一个现有的连接。`

![QQ截图20230807090815](https://github.com/CreatorMC/CreatorMCBlog/assets/103886337/45ffc2af-301b-4e53-a7f0-b63999dfea5f)

**Comment by CreatorMC** [comment]
在yml文件中设置了以下配置后，出现了其他的异常信息。

```yml
lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
```

异常信息：

`Redis command timed out; nested exception is io.lettuce.core.RedisCommandTimeoutException: Command timed out after 5 second(s)`

**Comment by CreatorMC** [comment]
```yml
lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        //改为1后仍有此问题
        min-idle: 1
```

**Comment by CreatorMC** [comment]
```yml
lettuce:
  cluster:
    refresh:
      adaptive: true
      period: 20
```

配置后仍有此问题
